name = "biblioteca-backend"
main = "src/index.js"
compatibility_date = "2024-09-23"

[vars]
ENVIRONMENT = "dev"
SENTRY_DSN = ""

[[d1_databases]]
binding = "DB"
database_name = "biblioteca-db-dev"
database_id = "3b9bea4a-2b83-4b6e-84fc-e673f8aa41e8"

[env.prod]
name = "biblioteca-backend-prod"

[env.prod.vars]
ENVIRONMENT = "prod"
SENTRY_DSN = ""

[[env.prod.d1_databases]]
binding = "DB"
database_name = "biblioteca-db-prod"
database_id = "ad96f290-173b-4e12-bd74-e6dbc8e33327"
